config/routes.rb
GenContractorMatching::Application.routes.draw do
  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  
  
  devise_for :users
  devise_for :contractors

  namespace :admin do
    root "base#index"
    resources :users
    
  end

  resources :contractors do
    collection do 
      get :edit_profile
      post :update_profile
      get :my_projects
      get :accept_project
    end
  end

  resources :projects do
  	collection do
  	  get :my_projects
      get :near_by_contractors
      get :assign_contractor
  	end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base

	acts_as_mappable :default_units => :miles,
	                   :default_formula => :sphere,
	                   :distance_field_name => :distance,
	                   :lat_column_name => :latitude,
	                   :lng_column_name => :longitude

  belongs_to :user
  belongs_to :contractor

  has_many :declined_contractors, :class_name => "DeclinedProject", :foreign_key => "project_id"

  ## Below method to fetch all the contractors with in 5 miles radius
  def near_by_contractors
  	relation = Contractor.within(5, origin: [self.latitude, self.longitude])
    relation = relation.where("(#{self.min_budget} BETWEEN contractors.min_budget AND contractors.max_budget) OR (#{self.max_budget} BETWEEN contractors.min_budget AND contractors.max_budget)")
    relation = self.declined_contractors.blank? ? relation : relation.where.not(id: self.declined_contractors.pluck(:contractor_id))
    relation.order(rating: :desc)
  end

  ["pending", "assigned", "wip", "closed"].each do |proj_status|
    define_method "#{proj_status}?" do 
      self.status == proj_status
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :get_project, only: [:edit, :update, :near_by_contractors]

  def index
  	@projects = Project.all
  end

  def my_projects
  	@projects = current_user.projects
  end

  def new
  	@project = Project.new
  end

 	def create
 		@project = Project.create(project_params)
 		if @project.update_attributes(user: current_user)
 			redirect_to my_projects_projects_path, success: 'Successfully created project'
 		end
 	end

 	def edit
 	end

 	def update
 		@project.update(project_params)
 		redirect_to my_projects_projects_path, success: 'Successfully updated project'
 	end

 	def near_by_contractors
 		@contractors = @project.near_by_contractors
 	end

 	def assign_contractor
 		@project = Project.find(params[:project])
 		@contractor = Contractor.find(params[:contractor])
 		@project.update_attributes(contractor: @contractor, status: 'assigned')
 		redirect_to my_projects_projects_path, success: "Successfully assiged project to #{@contractor.email}"
 	end
  
  private

  def get_project
  	@project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(
    :title,
    :latitude,
    :longitude,
    :min_budget,
    :max_budget,
    :design_service,
    :build_service
    )
  end
end

app/views/projects/_project_fields.html.erb
<div class="form-group">
  <%= f.label :title %>
  <div class="row">
    <div class="col-sm-6">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
</div>

<div class="form-group">
  <div class="row">
    <div class="col-sm-12">
      <%= f.label :Location %>
    </div>
    <div class="col-sm-3">
      <%= f.label :latitude %>
      <%= f.text_field :latitude, class: "form-control" %>
    </div>
    <div class="col-sm-3">
      <%= f.label :longitude %>
      <%= f.text_field :longitude, class: "form-control" %>
    </div>
  </div>
</div>

<div class="form-group">
  <div class="row">
    <div class="col-sm-12">
      <%= f.label :budget %>
    </div>
    <div class="col-sm-3">
      <%= f.label :min_budget %>
      <%= f.text_field :min_budget, class: "form-control" %>
    </div>
    <div class="col-sm-3">
      <%= f.label :max_budget %>
      <%= f.text_field :max_budget, class: "form-control" %>
    </div>
  </div>
</div>

<div class="form-group">
  <div class="row">
    <div class="col-sm-12">
      <%= f.label :type_of_service %>
    </div>
    <div class="col-sm-3">
      <%= f.label :design_service %>
      <%= f.check_box :design_service, class: "form-control" %>
    </div>
    <div class="col-sm-3">
      <%= f.label :build_service %>
      <%= f.check_box :build_service, class: "form-control" %>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Edit Project</h1>

    <%= form_for(@project, :as => :project,
    :url => project_path, method: :PATCH,
    :html => { :role => "form" }) do |f| %>

      <%= render partial: 'project_fields', locals: {f: f} %>

      <div class="row">
        <div class="col-sm-6">
          <%= f.submit "Update", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/projects/index.html.erb
<% title("User Projects") %>
<h1>Projects <small>Admin</small></h1>
<p><%#= link_to "Back to Admin", admin_root_path %></p>

<%#= form_tag admin_users_path, method: 'get', html: {role: "form"} do %>
<p>
  <%#= text_field_tag :search, params[:search] %>
  <%#= submit_tag "Search", :name => nil, class: "btn btn-sm btn-primary" %>
  <%#= link_to "All", admin_users_path, {class: "btn btn-sm btn-link"} %>
</p>
<%# end %>

<table class="table table-striped">
  <tr>
    <th>Title</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Min Budget</th>
    <th>Max Budget</th>
    <th>Type Of Service</th>
    <th>Created At</th>
  </tr>

  <% @projects.each do |project| %>

  <tr>
    <td><%= project.title %></td>
    <td><%= project.latitude %></td>
    <td><%= project.longitude %></td>
    <td><%= project.min_budget %></td>
    <td><%= project.max_budget %></td>
    <td><%= project.design_service? ? "Design Service" : project.build_service? ? "Build Service" : "NA" %></td>
    <td><%= project.created_at.to_date %></td>
  </tr>

  <% end %>

</table>
<!-- 
<div class="text-center">
  <p><%#= page_entries_info @users %></p>
  <%#= paginate @users %>
</div> -->

app/views/projects/my_projects.html.erb
<% title("User Projects") %>
<h1>Projects <small><%= current_user.email %></small></h1>
<p><%#= link_to "Back to Admin", admin_root_path %></p>

<%#= form_tag admin_users_path, method: 'get', html: {role: "form"} do %>
<p>
  <%#= text_field_tag :search, params[:search] %>
  <%#= submit_tag "Search", :name => nil, class: "btn btn-sm btn-primary" %>
  <%#= link_to "All", admin_users_path, {class: "btn btn-sm btn-link"} %>
</p>
<%# end %>

<table class="table table-striped">
  <tr>
    <th>Title</th>
    <th>Location</th>
    <th>Budget($)</th>
    <th>Type Of Service</th>
    <th>Created At</th>
    <th>Status</th>
    <th>Contractors Near by</th>
    <th>Action</th>
    <th>Contractor</th>
  </tr>

  <% @projects.each do |project| %>
    <tr>
      <td><%= project.title %></td>
      <td><%= "#{project.latitude}, #{project.longitude}"  %></td>
      <td><%= "#{project.min_budget} - #{project.max_budget}" %></td>
      <td><%= project.design_service? ? "Design Service" : project.build_service? ? "Build Service" : "NA" %></td>
      <td><%= project.created_at.to_date %></td>
      <td><%= project.status.capitalize  %></td>
      <td><%= link_to project.near_by_contractors.count, near_by_contractors_projects_path(id: project.id) if project.pending? %></td>
      <td><%= link_to "Edit", edit_project_path(id: project.id) if project.pending? %></td>
      <td><%= project.contractor.name if project.contractor %></td>
    </tr>
  <% end %>
</table>

app/views/projects/near_by_contractors.html.erb
<% title("Near By Contractors") %>
<h1>Contractors <small></small></h1>
<p><%#= link_to "Back to Admin", admin_root_path %></p>

<%#= form_tag admin_users_path, method: 'get', html: {role: "form"} do %>
<p>
  <%#= text_field_tag :search, params[:search] %>
  <%#= submit_tag "Search", :name => nil, class: "btn btn-sm btn-primary" %>
  <%#= link_to "All", admin_users_path, {class: "btn btn-sm btn-link"} %>
</p>
<%# end %>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Min Budget</th>
    <th>Max Budget</th>
    <th>Type Of Services</th>
    <th>Actions</th>
  </tr>

  <% @contractors.each do |contractor| %>
    <% if contractor.projects.count < 3  %>
      <tr>
        <td><%= contractor.name %></td>
        <td><%= contractor.min_budget %></td>
        <td><%= contractor.max_budget %></td>    
        <td>
          <% if contractor.offers_design_service? && contractor.offers_build_service? %>
            Design and Build Services
          <% elsif !contractor.offers_design_service? && contractor.offers_build_service? %>
            Build Service
          <% elsif contractor.offers_design_service? && !contractor.offers_build_service? %>
            Design Service
          <% else %>
            NA
          <% end %>
        </td>
        <td>
          <%= link_to "Assign", assign_contractor_projects_path(project: @project.id, contractor: contractor.id) %>
        </td>
      </tr>
    <% end %>
  <% end %>

</table>
<!-- 
<div class="text-center">
  <p><%#= page_entries_info @users %></p>
  <%#= paginate @users %>
</div> -->

app/views/projects/new.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>New Project</h1>

    <%= form_for(@project, :as => :project,
    :url => projects_path, method: :POST,
    :html => { :role => "form" }) do |f| %>

      <%= render partial: 'project_fields', locals: {f: f} %>

      <div class="row">
        <div class="col-sm-6">
          <%= f.submit "Create", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>

  </div>
</div>