config/routes.rb
GenContractorMatching::Application.routes.draw do
  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  
  
  devise_for :users
  devise_for :contractors

  namespace :admin do
    root "base#index"
    resources :users
    
  end

  resources :contractors do
    collection do 
      get :edit_profile
      post :update_profile
      get :my_projects
      get :accept_project
    end
  end

  resources :projects do
  	collection do
  	  get :my_projects
      get :near_by_contractors
      get :assign_contractor
  	end
  end

end

app/models/contractor.rb
class Contractor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	
	acts_as_mappable :default_units => :miles,
	                   :default_formula => :sphere,
	                   :distance_field_name => :distance,
	                   :lat_column_name => :latitude,
	                   :lng_column_name => :longitude
	                            
  has_many :projects
  has_many :declined_projects, :class_name => "DeclinedProject", :foreign_key => "contractor_id"
end

app/controllers/contractors_controller.rb
class ContractorsController < ApplicationController
  before_action :authenticate_contractor!
  before_action :get_contractor

  def edit_profile
  end

  def update_profile
  	if @contractor.update(contra_params)
      redirect_to edit_profile_contractors_path(id: @contractor.id), success: 'Updated Successfully'
    end
  end

  def my_projects
    @projects = @contractor.projects
  end
  
  def accept_project
    @project = Project.find(params[:id])
    if params[:status] == 'accepted'
      @project.update_attributes(status: 'wip')
    else
      @project.update_attributes(status: 'pending', contractor: nil)
      DeclinedProject.create(project: @project, contractor: @contractor)
    end
    redirect_to my_projects_contractors_path, success: "Project #{params[:status]} Successfully"
  end

  private

  def get_contractor
    @contractor = current_contractor
  end

  def contra_params
    params.require(:contractor).permit(
    :name,
    :latitude,
    :longitude,
    :min_budget,
    :max_budget,
    :offers_design_service,
    :offers_build_service
    )
  end
  
end

app/views/contractors/edit_profile.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Edit Profile</h1>

    <%= form_for(@contractor, :as => 'contractor',
    :url => update_profile_contractors_path(id: @contractor.id), method: :post,
    :html => { :role => "form" }) do |f| %>

    <div class="form-group">
      <%= f.label :name %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-sm-12">
          <%= f.label :Location %>
        </div>
        <div class="col-sm-3">
          <%= f.label :latitude %>
          <%= f.text_field :latitude, class: "form-control" %>
        </div>
        <div class="col-sm-3">
          <%= f.label :longitude %>
          <%= f.text_field :longitude, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-sm-12">
          <%= f.label :budget %>
        </div>
        <div class="col-sm-3">
          <%= f.label :min_budget %>
          <%= f.text_field :min_budget, class: "form-control" %>
        </div>
        <div class="col-sm-3">
          <%= f.label :max_budget %>
          <%= f.text_field :max_budget, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-sm-12">
          <%= f.label :type_of_services_offerd %>
        </div>
        <div class="col-sm-3">
          <%= f.label :offers_design_service %>
          <%= f.check_box :offers_design_service, class: "form-control" %>
        </div>
        <div class="col-sm-3">
          <%= f.label :offers_build_service %>
          <%= f.check_box :offers_build_service, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-6">
        <%= f.submit "Update", class: "btn btn-primary" %>
      </div>
    </div>
    <% end %>

  </div>
</div>

app/views/contractors/my_projects.html.erb
<% title("My Projects") %>
<h1>Projects <small><%= current_contractor.email %></small></h1>
<p><%#= link_to "Back to Admin", admin_root_path %></p>

<%#= form_tag admin_users_path, method: 'get', html: {role: "form"} do %>
<p>
  <%#= text_field_tag :search, params[:search] %>
  <%#= submit_tag "Search", :name => nil, class: "btn btn-sm btn-primary" %>
  <%#= link_to "All", admin_users_path, {class: "btn btn-sm btn-link"} %>
</p>
<%# end %>

<table class="table table-striped">
  <tr>
    <th>Title</th>
    <th>Location</th>
    <th>Budget($)</th>
    <th>Type Of Service</th>
    <th>Created At</th>
    <th>Status</th>
    <th>Home Owner</th>
    <th>Action</th>
  </tr>

  <% @projects.each do |project| %>
    <tr>
      <td><%= project.title %></td>
      <td><%= "#{project.latitude}, #{project.longitude}"  %></td>
      <td><%= "#{project.min_budget} - #{project.max_budget}" %></td>
      <td><%= project.design_service? ? "Design Service" : project.build_service? ? "Build Service" : "NA" %></td>
      <td><%= project.created_at.to_date %></td>
      <td><%= project.status.capitalize  %></td>
      <td><%= project.user.email %></td>
      <td>
        <%= link_to "Accept", accept_project_contractors_path(id: project.id, status: 'accepted') if project.assigned? %>
        <%= link_to "Deline", accept_project_contractors_path(id: project.id, status: 'declined') if project.assigned? %>
      </td>
    </tr>
  <% end %>

</table>
<!-- 
<div class="text-center">
  <p><%#= page_entries_info @users %></p>
  <%#= paginate @users %>
</div> -->