config/routes.rb
GenContractorMatching::Application.routes.draw do
  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  
  
  devise_for :users
  devise_for :contractors

  namespace :admin do
    root "base#index"
    resources :users
    
  end

  resources :contractors do
    collection do 
      get :edit_profile
      post :update_profile
      get :my_projects
      get :accept_project
    end
  end

  resources :projects do
  	collection do
  	  get :my_projects
      get :near_by_contractors
      get :assign_contractor
  	end
  end

end

app/views/layouts/_contractor_navigation_links.html.erb
<% if !contractor_signed_in? %>
		<li><%= link_to "Sign in", new_user_session_path %></li>
		<li><%= link_to "Sign up", new_user_registration_path %></li>
<% else %>
	<li><%= link_to "Protected Page", inside_path %></li>
	<li><%= link_to "Edit your account", edit_profile_contractors_path(id: current_contractor.id) %></li>
	<li><%= link_to "My Projects", my_projects_contractors_path %></li>
	<!-- <li><%#= link_to "Add Project", new_project_path %></li>
	<li><%#= link_to "My Projects", my_projects_projects_path %></li> -->	
	<li><%= link_to "Sign out", destroy_contractor_session_path, data:{method: :delete} %></li>
<% end %>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">

    <div class="row footer-first-row">

      <div class="col-xs-12 text-center">
        <p><small>
          &copy; <%= Time.now.year %> - Yourself!
          <br/>
          Assembled with <%= link_to "RailsBricks", "https://github.com/nicoschuele/railsbricks" %>
        </small></p>
      </div>

    </div>

  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
<% if msg.is_a?(String) %>
<div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
</div>
<% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <%= render 'layouts/navigation_links' %>
        <% elsif contractor_signed_in? %>
          <%= render 'layouts/contractor_navigation_links' %>
        <% else %>
          <li><%= link_to "User Sign in", new_user_session_path %></li>
          <li><%= link_to "User Sign up", new_user_registration_path %></li>
          <li><%= link_to "Contractor Sign in", new_contractor_session_path %></li>
          <li><%= link_to "Contractor Sign up", new_contractor_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if !user_signed_in? %>
	<li><%= link_to "Sign in", new_user_session_path %></li>
	<li><%= link_to "Sign up", new_user_registration_path %></li>
<% else %>
	<li><%= link_to "Protected Page", inside_path %></li>
	<li><%= link_to "Edit your account", edit_user_registration_path %></li>
	<li><%= link_to "Add Project", new_project_path %></li>
	<li><%= link_to "My Projects", my_projects_projects_path %></li>
	<% if current_user.admin? %>
		<li><%= link_to "Admin", admin_root_path %></li>
	<% end %>
	<li><%= link_to "Sign out", destroy_user_session_path, data:{method: :delete} %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || "GenContractorMatching" %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <div class="container">

      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 text-center">
          <%= render 'layouts/messages' %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12">
          <%= yield %>
        </div>
      </div>

    </div>
  </div>

  <%= render 'layouts/footer' %>

</body>
</html>